name: novodom_ds
description: "ds novodom"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.1.0
  intl: ^0.20.2
  value_provider:
    git:
      url: https://github.com/script972/valueProvider.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: WixMadeforText
      fonts:
        - asset: assets/fonts/WixMadeforText-VariableFont_wght.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
