name: novodom_ds
description: "ds novodom"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.1.0
  intl: ^0.19.0
  value_provider:
    git:
      url: https://github.com/script972/valueProvider.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/icons24/
    - assets/icons/icons16/
    - assets/icons/duotoneIcons/accent/
    - assets/icons/duotoneIcons/accent-wall/
    - assets/icons/duotoneIcons/accessibility/
    - assets/icons/duotoneIcons/arrow-down-circle/
    - assets/icons/duotoneIcons/arrow-left-circle/
    - assets/icons/duotoneIcons/arrow-right-circle/
    - assets/icons/duotoneIcons/arrow-up-circle/
    - assets/icons/duotoneIcons/back-square/
    - assets/icons/duotoneIcons/bar-chair/
    - assets/icons/duotoneIcons/bath/
    - assets/icons/duotoneIcons/bed/
    - assets/icons/duotoneIcons/bell/
    - assets/icons/duotoneIcons/brush/
    - assets/icons/duotoneIcons/calendar/
    - assets/icons/duotoneIcons/card/
    - assets/icons/duotoneIcons/carousel/
    - assets/icons/duotoneIcons/chair1/
    - assets/icons/duotoneIcons/chat/
    - assets/icons/duotoneIcons/check-circle/
    - assets/icons/duotoneIcons/clipboard/
    - assets/icons/duotoneIcons/close-circle/
    - assets/icons/duotoneIcons/closet/
    - assets/icons/duotoneIcons/closet2/
    - assets/icons/duotoneIcons/comment/
    - assets/icons/duotoneIcons/dark-light/
    - assets/icons/duotoneIcons/delete/
    - assets/icons/duotoneIcons/document/
    - assets/icons/duotoneIcons/edit/
    - assets/icons/duotoneIcons/element-plus/
    - assets/icons/duotoneIcons/export/
    - assets/icons/duotoneIcons/eye-open/
    - assets/icons/duotoneIcons/fail/
    - assets/icons/duotoneIcons/fridge/
    - assets/icons/duotoneIcons/import/
    - assets/icons/duotoneIcons/layers/
    - assets/icons/duotoneIcons/legal/
    - assets/icons/duotoneIcons/log-in/
    - assets/icons/duotoneIcons/log-out/
    - assets/icons/duotoneIcons/money-send/
    - assets/icons/duotoneIcons/more/
    - assets/icons/duotoneIcons/notebook-square/
    - assets/icons/duotoneIcons/pallete/
    - assets/icons/duotoneIcons/pdf/
    - assets/icons/duotoneIcons/pen-tool/
    - assets/icons/duotoneIcons/plan/
    - assets/icons/duotoneIcons/play/
    - assets/icons/duotoneIcons/plus-circle/
    - assets/icons/duotoneIcons/question/
    - assets/icons/duotoneIcons/refresh/
    - assets/icons/duotoneIcons/ruler/
    - assets/icons/duotoneIcons/rvt/
    - assets/icons/duotoneIcons/send/
    - assets/icons/duotoneIcons/signature/
    - assets/icons/duotoneIcons/success/
    - assets/icons/duotoneIcons/user-circle/
    - assets/icons/duotoneIcons/user-hand-up/
    - assets/icons/duotoneIcons/walls/
    - assets/icons/duotoneIcons/document_add/
    - assets/icons/duotoneIcons/floor-plan/
    - assets/icons/duotoneIcons/idesign/
    - assets/icons/duotoneIcons/measurements/
    - assets/icons/duotoneIcons/mood-board/
    - assets/icons/duotoneIcons/my-order/
    - assets/icons/duotoneIcons/permit-documents/
    - assets/icons/duotoneIcons/property-document/
    - assets/icons/duotoneIcons/quiestion-add/
    - assets/icons/duotoneIcons/we-design/

  fonts:
    - family: WixMadeforText
      fonts:
        - asset: assets/fonts/wixMadeforText/WixMadeforText-Regular.ttf
          weight: 400
        - asset: assets/fonts/wixMadeforText/WixMadeforText-Medium.ttf
          weight: 500
        - asset: assets/fonts/wixMadeforText/WixMadeforText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/wixMadeforText/WixMadeforText-Bold.ttf
          weight: 700
        - asset: assets/fonts/wixMadeforText/WixMadeforText-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
